export enum CategorieMission {
  LIVRAISON_COLIS = 'LIVRAISON_COLIS',
  DEMENAGEMENT_MEUBLES = 'DEMENAGEMENT_MEUBLES',
  DEMENAGEMENT_COMPLET = 'DEMENAGEMENT_COMPLET',
  LIVRAISON_COURSES = 'LIVRAISON_COURSES',
  MATERIAUX_CONSTRUCTION = 'MATERIAUX_CONSTRUCTION',
  GROS_OBJETS = 'GROS_OBJETS',
  PERSONNALISE = 'PERSONNALISE',
}
