export enum StatutMission {
  EN_ATTENTE = 'EN_ATTENTE',
  ACCEPTEE = 'ACCEPTEE',
  LIVREUR_EN_ROUTE = 'LIVREUR_EN_ROUTE',
  ARRIVE_RAMASSAGE = 'ARRIVE_RAMASSAGE',
  EN_LIVRAISON = 'EN_LIVRAISON',
  LIVRE = 'LIVRE',
  TERMINEE = 'TERMINEE',
  ANNULEE = 'ANNULEE',
}
