export enum StatutMission {
  EN_ATTENTE = 'EN_ATTENTE',
  ACCEPTEE = 'ACCEPTEE',
  EN_ROUTE = 'EN_ROUTE',
  ARRIVEE = 'ARRIVEE',
  EN_LIVRAISON = 'EN_LIVRAISON',
  LIVREE = 'LIVREE',
  LIVRE = 'LIVRE',
  TERMINEE = 'TERMINEE',
  ANNULEE = 'ANNULEE',
}
