export enum TypeNotification {
  NOUVELLE_MISSION = 'NOUVELLE_MISSION',
  MISSION_ACCEPTEE = 'MISSION_ACCEPTEE',
  MISSION_ANNULEE = 'MISSION_ANNULEE',
  STATUT_CHANGE = 'STATUT_CHANGE',
  CHANGEMENT_STATUT_MISSION = 'CHANGEMENT_STATUT_MISSION',
  NOUVEAU_MESSAGE = 'NOUVEAU_MESSAGE',
  LIVREUR_ARRIVE = 'LIVREUR_ARRIVE',
  MISSION_TERMINEE = 'MISSION_TERMINEE',
  NOUVELLE_EVALUATION = 'NOUVELLE_EVALUATION',
}
