export enum TypeVehicule {
  BICYCLETTE = 'BICYCLETTE',
  MOTO = 'MOTO',
  SCOOTER = 'SCOOTER',
  VOITURE = 'VOITURE',
  PICKUP = 'PICKUP',
  FOURGONNETTE = 'FOURGONNETTE',
  PETIT_CAMION = 'PETIT_CAMION',
  GROS_CAMION = 'GROS_CAMION',
}
