export enum TypeNotification {
  NOUVELLE_MISSION = 'NOUVELLE_MISSION',
  MISSION_ACCEPTEE = 'MISSION_ACCEPTEE',
  CHANGEMENT_STATUT_MISSION = 'CHANGEMENT_STATUT_MISSION',
  NOUVEAU_MESSAGE = 'NOUVEAU_MESSAGE',
  NOUVELLE_NOTE = 'NOUVELLE_NOTE',
  LIVREUR_ARRIVE = 'LIVREUR_ARRIVE',
}
